[build]
  command = "cd client && npm install && npm run build && cd ../server && npm install"
  publish = "client/build"  # Changed from dist to build for Create React App
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  
# Ensure client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200